config/routes.rb
Rails.application.routes.draw do
  get "food_groups/new"
  get "food_groups/create"
  devise_for :users, path: "profilo",
             path_names: {
               sign_in: "login",
               sign_out: "logout",
               password: "password",
               # confirmation: 'verifica-password',
               registration: "registrazione",
               sign_up: "crea"
             },
             controllers: {
               registrations: "users/registrations",
               sessions: "users/sessions"
             }

  authenticate :user, lambda { |u| u.admin? } do
    namespace :admin do
      resources :users
      resources :food_groups
      root to: "dashboard#index", as: :root
    end
  end
  get "privacy", to: "pages#privacy", as: :privacy
  get "privacy-registrazione", to: "pages#privacy_registration_page", as: :privacy_registration
  get "cookies", to: "pages#cookies", as: :cookies

  root "pages#index"
end

app/models/food_group.rb
class FoodGroup < ApplicationRecord
  validates :group_name, :name, :code, presence: true

  def self.ransackable_attributes(auth_object = nil)
    %w[group_name name code]
  end

  def self.ransackable_associations(auth_object = nil)
    []
  end
end

app/controllers/admin/food_groups_controller.rb
class Admin::FoodGroupsController < AdminController
  before_action :set_food_group, only: [:edit, :update, :destroy]
  def index
    authorize FoodGroup
    @q = policy_scope(FoodGroup).ransack(params[:q])
    @food_groups = @q.result.page(params[:page] || 1).per(20)
  end

  def new
    @food_group = policy_scope(FoodGroup).new()
    authorize @food_group
  end

  def create
    @food_group = policy_scope(FoodGroup).new(food_group_params)
    authorize @food_group
    if @food_group.save
      redirect_to admin_food_groups_path, success: t('labels.record_created')
    else
      render :new,  danger: "Impossibile creare il record: #{@food_group  .errors.full_messages}", status: :unprocessable_entity
    end
  end

  def edit
    authorize @food_group
  end

  def update
    authorize @food_group
    if @food_group.update(food_group_params)
      redirect_to admin_food_groups_path, success: t('labels.record_modified')
    else
      render :edit, danger: "Impossibile modificare il record: #{@food_group.errors.full_messages}", status: :unprocessable_entity
    end
  end

  def destroy
    authorize @food_group
    if @food_group.destroy
      redirect_to admin_food_groups_path, success: t('labels.record_destroyed'), status: :see_other
    else
      redirect_to admin_food_groups_path, danger: "Impossibile rimuovere il record: #{@food_group.errors.full_messages}", status: :unprocessable_entity
    end
  end

  protected

  def set_food_group
    @food_group = policy_scope(FoodGroup).find(params[:id])
  end

  def food_group_params
   params.require(:food_group).permit(:group_name, :name, :code)
  end
end

app/helpers/food_groups_helper.rb
module FoodGroupsHelper
end

app/views/admin/food_groups/_food_group.html.erb
<tr class="align-middle">
  <td><%= food_group.group_name %></td>
  <td><%= food_group.name %></td>
  <td><%= food_group.code %></td>
  <td>
    <%= link_to edit_admin_food_group_path(food_group), class: "text-decoration-none text-primary me-2" do %>
    <i class="fa-solid fa-pen-to-square" title="Modifica"></i>
    <% end %>
    <%= link_to admin_food_group_path(food_group), class: "text-decoration-none text-danger", data: { turbo_confirm: 'Sei sicuro di voler eliminare questo gruppo ?', turbo_method: :delete } do %>
     <i class="fa-solid fa-trash" title="Elimina"></i>
    <% end %>
  </td>
</tr>

app/views/admin/food_groups/_form.html.erb
<%= form_for [:admin, @food_group] do |f| %>
  <div class="mb-3 row">
    <%= f.label :name, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :group_name, class: "form-control", autofocus: true, required: 'required' %>
    </div>
  </div>

  <div class="mb-3 row">
    <%= f.label :name, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control", required: 'required' %>
    </div>
  </div>

  <div class="mb-3 row">
    <%= f.label :code, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :code, class: "form-control", required: 'required' %>
    </div>
  </div>

  <hr>
    <p class="form-control-static"><%= f.label :created_at, class: 'control-label' %>:
      <%=I18n.localize(f.object.created_at, format: :date_time) rescue 'n.d.' %></p>

  <p><%= f.label :updated_at, class: 'control-label' %>:
      <%= I18n.localize(f.object.updated_at, format: :date_time) rescue 'n.d.' %></p>

  <div class="form-group mb-2">
    <div class="d-flex">
      <%= button_tag type: 'submit', class: 'btn btn-primary me-5' do %>
        <span>Salva</span>
      <% end %>
      <%= button_tag type: 'reset',  class: 'btn btn-outline-primary' do %>
        <span>Reset</span>
      <% end %>
    </div>
  </div>

<% end %>

app/views/admin/food_groups/edit.html.erb
<%= render 'admin/food_groups/form' %>

app/views/admin/food_groups/index.html.erb
<%= link_to "Nuovo Gruppo", new_admin_food_group_path, class: "btn btn-primary mb-3" %>
<div class="collapse box mb-3" id="collapseFinder">
  <%= search_form_for @q, url: admin_food_groups_path, html: { role: 'search', id: 'search-box' } do |f| %>
    <div class="mb-3">
      <%= f.label ["Cerca per " + FoodGroup.human_attribute_name(:group_name), FoodGroup.human_attribute_name(:name), FoodGroup.human_attribute_name(:code)].join(', '), class: 'form-label' %>
      <%= f.search_field :group_name_or_name_or_code_cont, class: 'form-control' %>
    </div>

    <div class="d-flex justify-content-end">
      <%= link_to t('labels.cancel'), request.path, class: 'btn btn-link' %>
      <%= f.submit t('labels.search'), class: 'btn btn-primary' %>
  <% end %>
  </div>
</div>

<%- if @food_groups.any? -%>
  <table class="table mb-3 table-striped">
    <thead>
    <tr>
      <th class="sorting"><%= sort_link(@q, :group_name, FoodGroup.human_attribute_name(:group_name), {}, {class: "text-dark"}) %></th>
      <th class="sorting"><%= sort_link(@q, :name, FoodGroup.human_attribute_name(:name), {}, {class: "text-dark"}) %></th>
      <th class="sorting"><%= sort_link(@q, :code, FoodGroup.human_attribute_name(:code), {}, {class: "text-dark"}) %></th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    <%= render @food_groups %>
    </tbody>
  </table>
  <%= paginate @food_groups, params: {records: @food_groups} %>
<%- end -%>

app/views/admin/food_groups/new.html.erb
<%= render 'admin/food_groups/form' %>