config/routes.rb
Rails.application.routes.draw do
  get "food_groups/new"
  get "food_groups/create"
  devise_for :users, path: "profilo",
             path_names: {
               sign_in: "login",
               sign_out: "logout",
               password: "password",
               # confirmation: 'verifica-password',
               registration: "registrazione",
               sign_up: "crea"
             },
             controllers: {
               registrations: "users/registrations",
               sessions: "users/sessions"
             }

  authenticate :user, lambda { |u| u.admin? } do
    namespace :admin do
      resources :users
      resources :food_groups
      root to: "dashboard#index", as: :root
    end
  end
  get "privacy", to: "pages#privacy", as: :privacy
  get "privacy-registrazione", to: "pages#privacy_registration_page", as: :privacy_registration
  get "cookies", to: "pages#cookies", as: :cookies

  root "pages#index"
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  audited only: %i[name surname email active role
    privacy confirmed_at unconfirmed_email locked_at
  ]

  attr_accessor :privacy

  validates :name, :surname, :email, :role, presence: true
  validates :password, :password_confirmation, presence: true, on: :create
  validates :privacy, acceptance: true, on: :create
  validate :privacy_check, on: :create

  def admin?
     role == Role::ADMIN
  end

  def user?
     role == Role::USER
  end

  def self.ransackable_attributes(auth_object = nil)
    %w[active email surname name]
  end

  def self.ransackable_associations(auth_object = nil)
    []
  end

  def privacy_check
    errors.add(:privacy, :accepted) unless (@privacy.presence || "0") == "1"
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  before_action :set_user, only: [:edit, :update, :destroy]

  def index
    authorize User
    @q = policy_scope(User).ransack(params[:q])
    @users = @q.result.page(params[:page] || 1).per(20)
  end

  def new
    @user = policy_scope(User).new(role: Role::USER, active: true)
    authorize @user
  end

  def edit
    authorize @user
  end

  def create
    @user = policy_scope(User).new(user_params)
    authorize @user
    @user.password = @user.password_confirmation = generate_password
    if @user.save
      redirect_to get_referrer || admin_users_path, success: t('labels.record_created')
    else
      render :new,  danger: "Impossibile creare il record: #{@user.errors.full_messages}", status: :unprocessable_entity
    end
  end

  def update
    authorize @user
    if @user.update(user_params)
      redirect_to get_referrer || admin_users_path, success: t('labels.record_modified')
    else
      render :edit,  danger: "Impossibile modificare il record: #{@user.errors.full_messages}", status: :unprocessable_entity
    end
  end

  def destroy
    authorize @user

    if @user.destroy
      redirect_to get_referrer || admin_users_path, success: t('labels.record_destroyed'), status: :see_other
    else
      redirect_to get_referrer || admin_users_path, danger: "Impossibile rimuovere il record: #{@user.errors.full_messages}", status: :unprocessable_entity
    end
  end


  protected

  def set_user
    @user = policy_scope(User).find(params[:id])
  end

  def generate_password
    SecureRandom.hex
  end

  def user_params
   params.require(:user).permit(:active, :name, :surname, :email, :role)
  end

end

app/controllers/user/passwords_controller.rb
class User::PasswordsController < Devise::PasswordsController

  def update
    super
    unless current_user.nil?
      current_user.next_password_reminder = Settings.user.password_expiration_days.days.from_now.to_date
      current_user.save!
    end
  end
end

app/controllers/user/sessions_controller.rb
class User::SessionsController < Devise::SessionsController
  def after_sign_in_path_for(resource)
    root_path
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  def update
    super
    unless current_user.nil?
      current_user.next_password_reminder = Settings.user.password_expiration_days.days.from_now.to_date
      current_user.save!
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:
      %i[name surname email privacy]
    )
    devise_parameter_sanitizer.permit(:account_update, keys:
      %i[name surname email])
  end


  def after_inactive_sign_up_path_for(resource)
      root_path
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def after_sign_in_path_for(resource)
    root_path
  end
end

app/views/admin/users/_form.html.erb
<%= form_for [:admin, @user] do |f| %>
  <div class="form-check form-switch mb-3">
    <%= f.label :active, class: 'form-check-label' %>
    <%= f.check_box :active, class: 'form-check-input' %>
  </div>

  <div class="mb-3 row">
    <%= f.label :role, class: 'col-sm-2 control-label' %>
    <%= f.hidden_field :role %>
    <div class="col-sm-10">
      <%= f.select :role, options_for_select(Role.all, selected: f.object.role), {include_blank: I18n.t('helpers.select.prompt'), prompt: true}, class: 'form-control' %>
    </div>
  </div>
  <div class="mb-3 row">
    <%= f.label :name, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control", autofocus: true, required: 'required' %>
    </div>
  </div>

  <div class="mb-3 row">
    <%= f.label :surname, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :surname, class: "form-control", required: 'required' %>
    </div>
  </div>

  <div class="mb-3 row">
    <%= f.label :email, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :email, class: "form-control", required: 'required' %>
    </div>
  </div>

  <hr>


  <p><%= f.label :reset_password_sent_at, class: 'control-label' %>:
      <%=  I18n.localize(f.object.reset_password_sent_at, format: :date_time) rescue 'n.d.' %></p>


    <p class="form-control-static"><%= f.label :last_sign_in_at, class: 'control-label' %>:
      <%= I18n.localize(f.object.last_sign_in_at, format: :date_time) rescue 'n.d.' %></p>

    <p class="form-control-static"><%= f.label :created_at, class: 'control-label' %>:
      <%=I18n.localize(f.object.created_at, format: :date_time) rescue 'n.d.' %></p>

  <p><%= f.label :updated_at, class: 'control-label' %>:
      <%= I18n.localize(f.object.updated_at, format: :date_time) rescue 'n.d.' %></p>

  <div class="form-group mb-2">
    <div class="d-flex">
      <%= button_tag type: 'submit', class: 'btn btn-primary me-5' do %>
        <span>Salva</span>
      <% end %>
      <%= button_tag type: 'reset',  class: 'btn btn-outline-primary' do %>
        <span>Reset</span>
      <% end %>
    </div>
  </div>

<% end %>

app/views/admin/users/_user.html.erb
<tr class="align-middle">
  <td><%=
   #active_icon(user.active)
   %></td>
  <td><%= user.name %></td>
  <td><%= user.surname %></td>
  <td><%= user.email %></td>
  <td><%= user.role %></td>
  <td>
    <%= link_to edit_admin_user_path(user), class: "text-decoration-none text-primary me-2" do %>
    <i class="fa-solid fa-pen-to-square" title="Modifica"></i>
    <% end %>
    <%= link_to admin_user_path(user), class: "text-decoration-none text-danger", data: { turbo_confirm: 'Sei sicuro di voler eliminare questo utente?', turbo_method: :delete } do %>
     <i class="fa-solid fa-trash" title="Elimina"></i>
    <% end %>
  </td>
</tr>

app/views/admin/users/edit.html.erb
<%= render 'admin/users/form' %>

app/views/admin/users/index.html.erb
<button class="btn btn-primary mb-3" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFinder" aria-expanded="false" aria-controls="collapseFinder">
  Cerca utente
</button>
<%= link_to "Nuovo utente", new_admin_user_path,  class: "btn btn-primary mb-3" %>
<div class="collapse box mb-3" id="collapseFinder">
  <%= search_form_for @q, url: admin_users_path, html: { role: 'search', id: 'search-box' } do |f| %>
    <div class="mb-3">
      <%= f.label ["Cerca per " + User.human_attribute_name(:name), User.human_attribute_name(:surname), User.human_attribute_name(:email)].join(', '), class: 'form-label' %>
      <%= f.search_field :name_or_surname_or_email_cont, class: 'form-control' %>
    </div>

    <div class="d-flex justify-content-end">
      <%= link_to t('labels.cancel'), request.path, class: 'btn btn-link' %>
      <%= f.submit t('labels.search'), class: 'btn btn-primary' %>
  <% end %>
  </div>
</div>

<%- if @users.any? -%>
  <table class="table mb-3 table-striped">
    <thead>
    <tr>
      <th></th>
      <th class="sorting"><%= sort_link(@q, :name, User.human_attribute_name(:name), {}, {class: "text-dark"}) %></th>
      <th class="sorting"><%= sort_link(@q, :surname, User.human_attribute_name(:surname), {}, {class: "text-dark"}) %></th>
      <th class="sorting"><%= sort_link(@q, :email, {}, {class: "text-dark"}) %></th>
      <th class="sorting"><%= sort_link(@q, :role, {}, {class: "text-dark"}) %></th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    <%= render @users %>
    </tbody>
  </table>
  <%= paginate @users, params: {records: @users} %>

<%- end -%>

app/views/admin/users/new.html.erb
<%= render 'admin/users/form' %>