config/routes.rb
Rails.application.routes.draw do
  get "food_groups/new"
  get "food_groups/create"
  devise_for :users, path: "profilo",
             path_names: {
               sign_in: "login",
               sign_out: "logout",
               password: "password",
               # confirmation: 'verifica-password',
               registration: "registrazione",
               sign_up: "crea"
             },
             controllers: {
               registrations: "users/registrations",
               sessions: "users/sessions"
             }

  authenticate :user, lambda { |u| u.admin? } do
    namespace :admin do
      resources :users
      resources :food_groups
      root to: "dashboard#index", as: :root
    end
  end
  get "privacy", to: "pages#privacy", as: :privacy
  get "privacy-registrazione", to: "pages#privacy_registration_page", as: :privacy_registration
  get "cookies", to: "pages#cookies", as: :cookies

  root "pages#index"
end

app/views/admin/shared/_menu.html.erb
<nav class="navbar navbar-expand-lg bg-light navigation-bar mb-3">
  <div class="container container-fluid">
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Pannello di controllo", admin_root_path, class: "nav-link #{selected_menu([admin_root_path], {start_with: true})} " if policy(User).index? %>
        </li>
        <li class="nav-item">
          <%= link_to "Utenti", admin_users_path, class: "nav-link #{selected_menu([admin_users_path], {start_with: true})} " if policy(User).index? %>
        </li>
          <li class="nav-item">
          <%= link_to FoodGroup.model_name.human , admin_food_groups_path, class: "nav-link #{selected_menu([admin_food_groups_path], {start_with: true})} " if policy(FoodGroup).index? %>
        </li>
        <li class="nav-item">
          <%= link_to "Sito", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to t("labels.exit"), destroy_user_session_path, class: "nav-link", data: { turbo_method: :delete } %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/admin/shared/_notices.html.erb
<% flash.each do |flash_type, message| %>
  <div class="alert alert-<%= flash_type %> alert-dismissible fade show" role="alert">
  <%= message.html_safe %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>